classdef Mesh2D < steno3d.core.UserContent
%MESH2D Mesh for triangulated Steno3D Surface resources
%   This mesh provides the geometry for triangulated %%%ref[Surface](steno3d.core.Surface) resources. It
%   consists of an m x 3 array of spatial vertices and an n x 3 array of
%   vertex indices to define the triangles. Triangle values must be between
%   1 and m. `Mesh2D` has additional %%%ref[options](steno3d.core.opts.Mesh2DOptions) to customize the appearance of
%   the surface.
%
%   %%%properties
%
%   See the %%%ref[EXAMPLES](steno3d.core.examples.surface)
%
%   %%%seealso STENO3D.CORE.SURFACE, STENO3D.CORE.OPTS.MESH2DOPTIONS
%


    properties (Hidden, SetAccess = immutable)
        M2DProps = {                                                    ...
            struct(                                                     ...
                'Name', 'Vertices',                                     ...
                'Type', @props.Array,                                   ...
                'Doc', 'Spatial coordinates of surface vertices',       ...
                'Shape', {{'*', 3}},                                    ...
                'Binary', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Triangles',                                    ...
                'Type', @props.Array,                                   ...
                'Doc', 'Vertex indices of surface triangles',           ...
                'Shape', {{'*', 3}},                                    ...
                'DataType', 'int',                                      ...
                'Binary', true,                                         ...
                'IndexArray', true,                                     ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Options for the mesh',                          ...
                'Class', @steno3d.core.opts.Mesh2DOptions,              ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = Mesh2D(varargin)
            obj = obj@steno3d.core.UserContent(varargin{:});
        end
        function n = nN(obj)
            n = length(obj.Vertices);
        end
        function n = nC(obj)
            n = length(obj.Triangles);
        end
        function n = nbytes(obj)
            n = length(obj.Vertices(:))*8 + length(obj.Triangles(:))*8;
        end
    end

    methods (Hidden)
        function validator(obj)
            if min(obj.Triangles(:)) < 1 ||                             ...
                    max(obj.Triangles(:)) > size(obj.Vertices, 1)
                error('steno3d:mesh2DError',                            ...
                      ['Triangles must be integers between 1 and '      ...
                       num2str(size(obj.Vertices, 1))                   ...
                       ' (length of vertices)'])
            end
            if steno3d.utils.User.isLoggedIn()
                user = steno3d.utils.User.currentUser();
                sz = max([obj.([obj.PROP_PREFIX 'Vertices']).nbytes     ...
                          obj.([obj.PROP_PREFIX 'Triangles']).nbytes]);
                if sz > user.FileSizeLimit
                    error('steno3d:mesh2DError',                        ...
                          ['File size ' num2str(sz) ' bytes exceeds '   ...
                           'file limit of ' num2str(user.FileSizeLimit) ...
                           ' bytes']);
                end
            end
        end
        function args = uploadArgs(obj)
            vStruct = obj.PR_Vertices.serialize();
            tStruct = obj.PR_Triangles.serialize();
            args = {'vertices', vStruct.FileID,                         ...
                    'verticesType', vStruct.DType,                      ...
                    'triangles', tStruct.FileID,                        ...
                    'trianglesType', tStruct.DType};
            args = [args, uploadArgs@steno3d.core.UserContent(obj)];
        end
    end
end

