classdef LineBinder < props.HasProps
%LINEBINDER Bind data to segments or vertices of a Steno3D Line
%   For usage details, see the %%%ref[binders help](steno3d.core.binders).
%
%   %%%properties
%
%   See the line %%%ref[EXAMPLES](steno3d.examples.core.line)
%
%   %%%seealso steno3d.core.binders, steno3d.core.DataArray, steno3d.core.Line
%


    properties (Hidden, SetAccess = immutable)
        LBinderProps = {                                                ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                                  ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'CC', {{'FACE', 'FACES', 'CELLCENTER', 'SEGMENT',   ...
                            'CELLCENTERS','EDGE', 'EDGES', 'SEGMENTS'}},...
                    'N', {{'VERTEX', 'VERTICES', 'NODE', 'NODES',       ...
                           'ENDPOINT', 'ENDPOINTS'}}                    ...
                ),                                                      ...
                'ValidateDefault', false,                               ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Line data array',                               ...
                'Class', @steno3d.core.DataArray,                       ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = LineBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end
end

