classdef SurfaceBinder < props.HasProps
%SURFACEBINDER Bind data to faces or vertices of a Steno3D Surface
%   For usage details, see the %%%ref[binders help](steno3d.core.binders).
%
%   %%%properties
%
%   See the surface %%%ref[EXAMPLES](steno3d.core.examples.surface)
%
%   %%%seealso STENO3D.CORE.BINDERS, STENO3D.CORE.DATAARRAY,
%   STENO3D.CORE.SURFACE
%


    properties (Hidden, SetAccess = immutable)
        SBidnerProps = {                                                ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                                  ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'CC', {{'FACE', 'FACES', 'CELLCENTER',              ...
                            'CELLCENTERS', 'TRIANGLE', 'TRIANGLES'}},   ...
                    'N', {{'VERTEX', 'VERTICES', 'NODE', 'NODES'}}      ...
                ),                                                      ...
                'ValidateDefault', false,                               ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Surface data array',                            ...
                'Class', @steno3d.core.DataArray,                       ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = SurfaceBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end
end

