classdef VolumeBinder < props.HasProps
%VOLUMEBINDER Bind data to cell centers of a Steno3D Volume
%   For usage details, see the %%%ref[binders help](steno3d.core.binders).
%
%   %%%properties
%
%   See the volume %%%ref[EXAMPLES](steno3d.examples.core.volume)
%
%   %%%seealso steno3d.core.binders, steno3d.core.DataArray, steno3d.core.Volume
%


    properties (Hidden, SetAccess = immutable)
        VBinderProps = {                                                ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                                  ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'CC', {{'CELLCENTER', 'CELL', 'CELLS',              ...
                            'CELLCENTERS'}}                             ...
                ),                                                      ...
                'DefaultValue', 'CC',                                   ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Volume data array',                             ...
                'Class', @steno3d.core.DataArray,                       ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = VolumeBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end
end

