function success = testSteno3D(raiseError, attemptUpload)
%TESTSTENO3D Test suite for steno3d

    if nargin < 1
        raiseError = false;
    end
    if nargin < 2
        attemptUpload = false;
    end
    success = true;
    try
        pngfile = [tempname '.png'];
        imwrite([1 2 3; 4 5 6; 7 8 9], pngfile);
        p = steno3d.core.Project(                                       ...
            'Title', 'MATLAB Test Project',                             ...
            'Description', 'Just a test',                               ...
            'Public', false                                             ...
        );

        pt = steno3d.core.Point(                                        ...
            'Title', 'Test Points',                                     ...
            'Mesh', steno3d.core.Mesh0D(                                ...
                'Vertices', rand(100, 3)                                ...
            ),                                                          ...
            'Data', {{                                                  ...
                'Location', 'CC', 'Data', {                             ...
                    'Title', 'Rand 1', 'Array', rand(100, 1)            ...
                }                                                       ...
            }, {                                                        ...
                'Location', 'CC', 'Data', {                             ...
                    'Title', 'Rand 2', 'Array', rand(100, 1)            ...
                }                                                       ...
            }},                                                         ...
            'Textures', {                                               ...
                steno3d.core.Texture2DImage(                            ...
                    'Title', 'Temp tex',                                ...
                    'O', [.5 .5 .5],                                    ...
                    'U', [.5 0 0],                                      ...
                    'V', [0 .5 0],                                      ...
                    'Image', pngfile                                    ...
                )                                                       ...
            },                                                          ...
            'Opts', {'Color', 'k'}                                      ...
        );

        li = steno3d.core.Line(                                         ...
            'Title', 'Test Line',                                       ...
            'Description', 'Just a line',                               ...
            'Mesh', {                                                   ...
                'Vertices', rand(100, 3),                               ...
                'Segments', randi(100, [50, 2]),                        ...
                'Opts', {'View_Type', 'line'}                           ...
            },                                                          ...
            'Data', {{                                                  ...
                'Location', 'CC', 'Data', {                             ...
                    'Title', 'Rand 1', 'Array', rand(50, 1)             ...
                }                                                       ...
            }, {                                                        ...
                'Location', 'N', 'Data', {                              ...
                    'Title', 'Rand 2', 'Array', rand(100, 1)            ...
                }                                                       ...
            }},                                                         ...
            'Opts', {'Opacity', .5, 'Color', 'r'}                       ...
        );

        s1 = steno3d.core.Surface(                                      ...
            'Title', 'Test Grid Surface',                               ...
            'Mesh', {'H1', randi(5, 1, 3),                              ...
                     'H2', randi(5, 1, 4),                              ...
                     'O', [0 0 5],                                      ...
                     'U', [1 0 0],                                      ...
                     'V', [-.05 1 0],                                   ...
                     'Z', rand(20, 1),                                  ...
                     'Opts', {'Wireframe', true}},                      ...
            'Data', {{                                                  ...
                'Location', 'CC', 'Data', {                             ...
                    'Title', 'Rand 1', 'Array', rand(12, 1)             ...
                }                                                       ...
            }, {                                                        ...
                'Location', 'N', 'Data', {                              ...
                    'Title', 'Rand 2', 'Array', rand(20, 1)             ...
                }                                                       ...
            }},                                                         ...
            'Textures', steno3d.core.Texture2DImage(                    ...
                'Title', 'Temp tex',                                    ...
                'O', [.5 .5 .5],                                        ...
                'U', [.5 0 0],                                          ...
                'V', [0 .5 0],                                          ...
                'Image', pngfile                                        ...
            ),                                                          ...
            'Opts', {'Opacity', .5, 'Color', 'r'}                       ...
        );

        s2 = steno3d.core.Surface(                                      ...
            'Title', 'Test Tri Surface',                                ...
            'Mesh', steno3d.core.Mesh2D(                                ...
                'Vertices', rand(100, 3),                               ...
                'Triangles', randi(100, [50, 3]),                       ...
                'Opts', steno3d.core.opts.Mesh2DOptions(                ...
                    'Wireframe', false                                  ...
                )                                                       ...
            ),                                                          ...
            'Data', {steno3d.core.binders.SurfaceBinder(                ...
                'Location', 'CC', 'Data', steno3d.core.DataArray(       ...
                    'Title', 'Rand 1', 'Array', rand(50, 1)             ...
                )                                                       ...
            ), steno3d.core.binders.SurfaceBinder(                      ...
                'Location', 'N', 'Data', steno3d.core.DataArray(        ...
                    'Title', 'Rand 2', 'Array', rand(100, 1)            ...
                )                                                       ...
            )},                                                         ...
            'Textures', steno3d.core.Texture2DImage(                    ...
                'Title', 'Temp tex',                                    ...
                'O', [.5 .5 .5],                                        ...
                'U', [.5 0 0],                                          ...
                'V', [0 .5 0],                                          ...
                'Image', pngfile                                        ...
            ),                                                          ...
            'Opts', steno3d.core.opts.SurfaceOptions(                   ...
                'Opacity', .5, 'Color', 'r'                             ...
            )                                                           ...
        );

        vo = steno3d.core.Volume(                                       ...
            'Title', 'Test Volume',                                     ...
            'Description', 'Just a volume',                             ...
            'Mesh', steno3d.core.Mesh3DGrid(                            ...
                'H1', randi(5, 1, 3),                                   ...
                'H2', randi(5, 1, 4),                                   ...
                'H3', randi(5, 1, 5),                                   ...
                'O', [5 5 10]                                           ...
            ),                                                          ...
            'Data', {                                                   ...
                'Data', rand(60, 1)                                     ...
            },                                                          ...
            'Opts', {'Color', [.2 .2 .5]}                               ...
        );

        p.Resources = {pt, li, s1, s2, vo};

        p.validate;

        if attemptUpload
            steno3d.login;
            p.upload;
        end

    catch ME
        success = false;
        if raiseError
            rethrow(ME);
        end
    end

end

