function matverchk
%MATVERCHK Error if the MATLAB version is invalid, < 8.4 (R2014b)

    if verLessThan('matlab', '8.4')
        error('steno3d:matlabError', ['Steno3D requires MATLAB '        ...
              'Release R2014b (8.4) or greater.\nIf you do not have '   ...
              'access to this version, consider trying the\n<a href="'  ...
              'matlab: web(''https://github.com/3ptscience/steno3dpy/'''...
              ', ''-browser'')">Steno3D client library for Python</a>.']);
    end
end

