classdef LineBinder < props.HasProps
%LINEBINDER Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        LBinderProps = {                                                ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                                  ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'CC', {{'LINE', 'FACE', 'CELLCENTER', 'EDGE',       ...
                            'SEGMENT'}},                                ...
                    'N', {{'VERTEX', 'NODE', 'ENDPOINT'}}               ...
                ),                                                      ...
                'ValidateDefault', false,                               ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Line data array',                               ...
                'Class', @steno3d.core.DataArray,                       ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = LineBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end

end

