classdef PointBinder < props.HasProps
%POINTBINDER Object to add data to steno3d Point


    properties (Hidden, SetAccess = immutable)
        PBinderProps = {                                                ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                                  ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'N', {{'VERTEX', 'NODE', 'CC', 'CELLCENTER'}}       ...
                ),                                                      ...
                'DefaultValue', 'N',                                    ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Point data array',                              ...
                'Class', @steno3d.core.DataArray,                       ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = PointBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end

end

