classdef SurfaceBinder < props.HasProps
%SURFACEBINDER Bind data to faces or vertices of a Steno3D Surface
%   For usage details, see the <a href="matlab: help steno3d.core.binders
%   ">binders help</a>.
%
%   SURFACEBINDER implements <a href="matlab: help props.HasProps
%   ">HasProps</a> for dynamic, type-checked <a href="matlab:
%   help props.Prop">properties</a>
%
%   REQUIRED PROPERTIES:
%       Location (<a href="matlab: help props.String">props.String</a>)
%           Location of the data on mesh
%           Choices: CC, N
%
%       Data (<a href="matlab: help props.Instance">props.Instance</a>)
%           Surface data array
%           Class: <a href="matlab: help steno3d.core.DataArray
%           ">DataArray</a>
%
%
%   See the surface <a href="matlab: help steno3d.core.examples.point
%   ">EXAMPLES</a>
%
%   See also STENO3D.CORE.BINDERS, STENO3D.CORE.DATAARRAY,
%   STENO3D.CORE.SURFACE
%


    properties (Hidden, SetAccess = immutable)
        SBidnerProps = {                                                ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                                  ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'CC', {{'FACE', 'FACES', 'CELLCENTER',              ...
                            'CELLCENTERS', 'TRIANGLE', 'TRIANGLES'}},   ...
                    'N', {{'VERTEX', 'VERTICES', 'NODE', 'NODES'}}      ...
                ),                                                      ...
                'ValidateDefault', false,                               ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Surface data array',                            ...
                'Class', @steno3d.core.DataArray,                       ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = SurfaceBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end
end

