classdef SurfaceBinder < props.HasProps
%SURFACEBINDER Object to add data to steno3d Surface

    properties (Hidden, SetAccess = immutable)
        SBidnerProps = {                                                ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                                  ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'CC', {{'FACE', 'CELLCENTER'}},                     ...
                    'N', {{'VERTEX', 'NODE', 'CORNER'}}                 ...
                ),                                                      ...
                'ValidateDefault', false,                               ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Surface data array',                            ...
                'Class', @steno3d.core.DataArray,                       ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = SurfaceBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end

end

