classdef VolumeBinder < props.HasProps
%VOLUMEBINDER Bind data to cell centers of a Steno3D Volume
%   For usage details, see the <a href="matlab: help steno3d.core.binders
%   ">binders help</a>.
%
%   VOLUMEBINDER implements <a href="matlab: help props.HasProps
%   ">HasProps</a> for dynamic, type-checked <a href="matlab:
%   help props.Prop">properties</a>
%
%   REQUIRED PROPERTIES:
%       Location (<a href="matlab: help props.String">props.String</a>)
%           Location of the data on mesh
%           Choices: CC
%           Default: 'CC'
%
%       Data (<a href="matlab: help props.Instance">props.Instance</a>)
%           Volume data array
%           Class: <a href="matlab: help steno3d.core.DataArray
%           ">DataArray</a>
%
%
%   See the volume <a href="matlab: help steno3d.core.examples.volume
%   ">EXAMPLES</a>
%
%   See also STENO3D.CORE.BINDERS, STENO3D.CORE.DATAARRAY,
%   STENO3D.CORE.VOLUME
%


    properties (Hidden, SetAccess = immutable)
        VBinderProps = {                                                ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                                  ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'CC', {{'CELLCENTER', 'CELL', 'CELLS',              ...
                            'CELLCENTERS'}}                             ...
                ),                                                      ...
                'DefaultValue', 'CC',                                   ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Volume data array',                             ...
                'Class', @steno3d.core.DataArray,                       ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = VolumeBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end
end

