classdef VolumeBinder < props.HasProps
%VOLUMEBINDER Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        VBinderProps = {                                               ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @props.String,                         ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'CC', {{'CELLCENTER'}}                              ...
                ),                                                      ...
                'DefaultValue', 'CC',                                   ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Instance,                       ...
                'Doc', 'Volume data array',                             ...
                'Class', @steno3d.core.DataArray,                  ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = VolumeBinder(varargin)
            obj = obj@props.HasProps(varargin{:});
        end
    end

end

