classdef PropTestClass < props.HasProps
%PROPTESTCLASS Summary of this class goes here
%   Detailed explanation goes here
%
%   OPTIONAL PROPERTIES:
%       ThreeColumns (props.Array)
%           Three column array, saved as binary
%           Shape: {*, 3}, DataType: float
%
%       IsSomething (props.Bool)
%           Is it something?
%
%       FaceColor (props.Color)
%           Color of the object
%
%       PositiveFloat (props.Float)
%           A positive number
%           Minimum: 0, 
%
%       SomePicture (props.Image)
%           Some PNG image
%
%       FigureInstance (props.Instance)
%           An auto-created figure property
%           Class: matlab.ui.Figure
%
%       Int0to10 (props.Int)
%           An integer between 0 and 10
%           Minimum: 0, Maximum: 10
%
%       MultipleColors (props.Repeated)
%           This propery can hold multiple colors
%           Prop type: props.Color
%
%       AnyString (props.String)
%           This property can be any string
%
%       ChoiceString (props.String)
%           This property can only be hi or bye
%           Choices: hi, bye
%
%       CoercedChoiceString (props.String)
%           This coerces hi and bye to English
%           Choices: hi, bye
%
%       StringOrInt (props.Union)
%           This property is a string or an int>0
%           Prop types: props.Int, props.String
%
%       ViewDirection (props.Vector)
%           Three-component view direction vector
%           Shape: {1, 3}, DataType: float
%
%   See also props.Array, props.Bool, props.Color, props.Float, props.HasProps, props.Image, props.Instance, props.Int, props.Repeated, props.String, props.Union, props.Vector

    properties (Hidden, SetAccess = immutable)
        ArrayPropStruct = {                                     ...
            struct(                                             ...
                'Name', 'ThreeColumns',                         ...
                'Type', @props.Array,                           ...
                'Doc', 'Three column array, saved as binary',   ...
                'Shape', {{'*', 3}},                            ...
                'Binary', true,                                 ...
                'DataType', 'float'                             ...
            )                                                   ...
        }
        BoolPropStruct = {                                      ...
            struct(                                             ...
                'Name', 'IsSomething',                          ...
                'Type', @props.Bool,                            ...
                'Doc', 'Is it something?',                      ...
                'DefaultValue', true                            ...
            )                                                   ...
        }
        ColorPropStruct = {                                     ...
            struct(                                             ...
                'Name', 'FaceColor',                            ...
                'Type', @props.Color,                           ...
                'Doc', 'Color of the object',                   ...
                'DefaultValue', 'random'                        ...
            )                                                   ...
        }
        FloatPropStruct = {                                     ...
            struct(                                             ...
                'Name', 'PositiveFloat',                        ...
                'Type', @props.Float,                           ...
                'Doc', 'A positive number',                     ...
                'MinValue', 0                                   ...
            )                                                   ...
        }
        ImagePropStruct = {                                     ...
            struct(                                             ...
                'Name', 'SomePicture',                          ...
                'Type', @props.Image,                           ...
                'Doc', 'Some PNG image'                         ...
            )                                                   ...
        }
        InstancePropStruct = {                                  ...
            struct(                                             ...
                'Name', 'FigureInstance',                       ...
                'Type', @props.Instance,                        ...
                'Doc', 'An auto-created figure property',       ...
                'Class', @matlab.ui.Figure,                     ...
                'Initialize', true                             ...
            )                                                   ...
        }
        IntPropStruct = {                                       ...
            struct(                                             ...
                'Name', 'Int0to10',                             ...
                'Type', @props.Int,                             ...
                'Doc', 'An integer between 0 and 10',           ...
                'MinValue', 0,                                  ...
                'MaxValue', 10                                  ...
            )                                                   ...
        }
        RepeatedPropStruct = {                                  ...
            struct(                                             ...
                'Name', 'MultipleColors',                       ...
                'Type', @props.Repeated,                        ...
                'Doc', 'This propery can hold multiple colors', ...
                'PropType', struct(                             ...
                    'Type', @props.Color                        ...
                )                                               ...
            )                                                   ...
        }
        StringPropsStruct = {                                   ...
            struct(                                             ...
                'Name', 'AnyString',                            ...
                'Type', @props.String,                          ...
                'Doc', 'This property can be any string'        ...
            ), struct(                                          ...
                'Name', 'ChoiceString',                         ...
                'Type', @props.String,                          ...
                'Doc', 'This property can only be hi or bye',   ...
                'Choices', {{'hi', 'bye'}},                     ...
                'DefaultValue', 'hi'                            ...
            ), struct(                                          ...
                'Name', 'CoercedChoiceString',                  ...
                'Type', @props.String,                          ...
                'Doc', 'This coerces hi and bye to English',    ...
                'Choices', struct(                              ...
                    'hi', {{'hola', 'bonjour', 'guten tag'}},   ...
                    'bye', {{'adios', 'au revoir',              ...
                             'auf Wiedersehen'}}                ...
                ),                                              ...
                'DefaultValue', 'hi'                            ...
            )                                                   ...
        }
        UnionPropStruct = {                                     ...
            struct(                                             ...
                'Name', 'StringOrInt',                          ...
                'Type', @props.Union,                           ...
                'Doc', 'This property is a string or an int>0', ...
                'PropTypes', {{struct(                          ...
                    'Type', @props.Int,                         ...
                    'MinValue', 0                               ...
                ), struct(                                      ...
                    'Type', @props.String                       ...
                )}}                                             ...
            )                                                   ...
        }
        VectorPropStruct = {                                    ...
            struct(                                             ...
                'Name', 'ViewDirection',                        ...
                'Type', @props.Vector,                          ...
                'Doc', 'Three-component view direction vector', ...
                'DefaultValue', 'Z'                             ...
            )                                                   ...
        }
    end
    
    methods
        function div(obj)
            b = 5 \ 6;
        end
    end
    
end

