classdef Mesh2DOptions < steno3d.core.Options
%MESH2DOPTIONS Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        M2DOptTraits = {                                                ...
            struct(                                                     ...
                'Name', 'Wireframe',                                    ...
                'Type', @steno3d.traits.Bool,                           ...
                'Doc', 'Display 2D mesh wireframe',                     ...
                'DefaultValue', false,                                  ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = Mesh2DOptions(varargin)
            obj = obj@steno3d.core.Options(varargin{:});
        end
    end

end

