classdef Mesh2DGrid < steno3d.core.UserContent
%MESH2DGRID Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        M2DTraits = {                                                   ...
            struct(                                                     ...
                'Name', 'H1',                                           ...
                'Type', @steno3d.traits.Array,                          ...
                'Doc', 'Mesh2D grid cell widths, U-direction',          ...
                'Shape', {{1, '*'}},                                       ...
                'Serial', false,                                        ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'H2',                                           ...
                'Type', @steno3d.traits.Array,                          ...
                'Doc', 'Mesh2D grid cell widths, V-direction',          ...
                'Shape', {{1, '*'}},                                       ...
                'Serial', false,                                        ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'O',                                            ...
                'Type', @steno3d.traits.Vector,                         ...
                'Doc', 'Origin vector',                                 ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'U',                                            ...
                'Type', @steno3d.traits.Vector,                         ...
                'Doc', 'Orientation of H1 axis',                        ...
                'DefaultValue', 'X',                                    ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'V',                                            ...
                'Type', @steno3d.traits.Vector,                         ...
                'Doc', 'Orientation of H2 axis',                        ...
                'DefaultValue', 'Y',                                    ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Z',                                            ...
                'Type', @steno3d.traits.Array,                          ...
                'Doc', 'Node topography',                               ...
                'Shape', {{'*'}},                                       ...
                'Serial', true,                                         ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Mesh2D options',                                ...
                'Class', @steno3d.core.surface.Mesh2DOptions,           ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
        function obj = Mesh2DGrid(varargin)
            obj = obj@steno3d.core.UserContent(varargin{:});
        end
    end
    
    methods (Hidden)
        function args = uploadArgs(obj)
            
            args = {'tensors', ['{"h1": "' obj.TR_H1.serialize()        ...
                                '", "h2": "' obj.TR_H2.serialize()      ...
                                '"}'],                                  ...
                    'OUV', ['{"O": "' obj.TR_O.serialize()              ...
                            '", "U": "' obj.TR_U.serialize()            ...
                            '", "V": "' obj.TR_V.serialize() '"}']};
            
            zStruct = obj.TR_Z.serialize();
            args = [args, {'array', zStruct.FileID,                     ...
                           'arrayType', zStruct.DType}];
                       
            args = [args, uploadArgs@steno3d.core.UserContent(obj)];
        end
    end

end

