classdef Mesh2D < steno3d.core.UserContent
%MESH2D Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        M2DTraits = {                                                   ...
            struct(                                                     ...
                'Name', 'Vertices',                                     ...
                'Type', @steno3d.traits.Array,                          ...
                'Doc', 'Mesh2D vertices',                               ...
                'Shape', {{'*', 3}},                                    ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Triangles',                                    ...
                'Type', @steno3d.traits.Array,                          ...
                'Doc', 'Mesh2D triangle vertex indices',                ...
                'Shape', {{'*', 3}},                                    ...
                'DataType', 'int',                                      ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Mesh2D options',                                ...
                'Class', @steno3d.core.surface.Mesh2DOptions,           ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
        function obj = Mesh2D(varargin)
            obj = obj@steno3d.core.UserContent(varargin{:});
        end
    end
    
    methods (Hidden)
        function args = uploadArgs(obj)
            
            vStruct = obj.TR_Vertices.serialize();
            tStruct = obj.TR_Triangles.serialize();
            args = {'vertices', vStruct.FileID,              ...
                    'verticesType', vStruct.DType,           ...
                    'triangles', tStruct.FileID,              ...
                    'trianlgesType', tStruct.DType};
                       
            args = [args, uploadArgs@steno3d.core.UserContent(obj)];
        end
    end

end

