classdef SurfaceOptions < steno3d.core.Options
%SURFACEOPTIONS Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        SOptTraits = {                                                  ...
            struct(                                                     ...
                'Name', 'Color',                                        ...
                'Type', @steno3d.traits.Color,                          ...
                'Doc', 'Solid surface color',                           ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opacity',                                      ...
                'Type', @steno3d.traits.Float,                          ...
                'Doc', 'Surface opacity',                               ...
                'MinValue', 0,                                          ...
                'MaxValue', 1,                                          ...
                'Required', false,                                      ...
                'DefaultValue', 1                                       ...
            )                                                           ...

        }
    end

    methods
        
        function obj = SurfaceOptions(varargin)
            obj = obj@steno3d.core.Options(varargin{:});
        end
    end

end

