classdef Surface < steno3d.core.CompositeResource
%SURFACE Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        SurfaceTraits = {                                               ...
            struct(                                                     ...
                'Name', 'Mesh',                                         ...
                'Type', @steno3d.traits.Union,                          ...
                'Doc', 'Surface mesh',                                  ...
                'TraitTypes', {{struct(                                 ...
                    'Type', @steno3d.traits.Instance,                   ...
                    'Class', @steno3d.core.surface.Mesh2D               ...
                ), struct(                                              ...
                    'Type', @steno3d.traits.Instance,                   ...
                    'Class', @steno3d.core.surface.Mesh2DGrid           ...
                )}},                                                    ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @steno3d.traits.Repeated,                       ...
                'Doc', 'Surface data',                                  ...
                'TraitType', struct(                                    ...
                    'Type', @steno3d.traits.Instance,                   ...
                    'Class', @steno3d.core.surface.SurfaceBinder,       ...
                    'Initialize', false                                 ...
                ),                                                      ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Textures',                                     ...
                'Type', @steno3d.traits.Repeated,                       ...
                'Doc', 'Surface textures',                              ...
                'TraitType', struct(                                    ...
                    'Type', @steno3d.traits.Instance,                   ...
                    'Class', @steno3d.core.texture.Texture2DImage,      ...
                    'Initialize', false                                 ...
                ),                                                      ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Surface Options',                               ...
                'Class', @steno3d.core.surface.SurfaceOptions,          ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = Surface(varargin)
            obj = obj@steno3d.core.CompositeResource(varargin{:});
        end
    end

end

