classdef SurfaceOptions < steno3d.traits.HasTraits
%SURFACEOPTIONS Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        SOptTraits = {                                                  ...
            struct(                                                     ...
                'Name', 'Color',                                        ...
                'Type', @steno3d.traits.Color,                          ...
                'Doc', 'Solid surface color',                           ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opacity',                                      ...
                'Type', @steno3d.traits.Number,                         ...
                'Doc', 'Surface opacity',                               ...
                'MinValue', 0,                                          ...
                'MaxValue', 1,                                          ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
    end

end

