classdef Mesh1DOptions < steno3d.traits.HasTraits
%MESH1DOPTIONS Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        M1DOptTraits = {                                                ...
            struct(                                                     ...
                'Name', 'ViewType',                                     ...
                'Type', @steno3d.traits.String,                         ...
                'Doc', ['Display 1D lines or tubes/boreholes/extruded ' ...
                        'lines'],                                       ...
                'Choices', struct(                                      ...
                    'line', {{'lines', 'tube', '1d'}},                  ...
                    'tube', {{'tubes', 'extruded line',                 ...
                              'extruded lines', 'borehole',             ...
                              'boreholes'}}                             ...
                ),                                                      ...
                'DefaultValue', 'line',                                 ...
                'Lowercase', true,                                      ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
    end

end

