classdef Mesh1D < steno3d.core.UserContent
%MESH1D Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        M1DTraits = {                                                   ...
            struct(                                                     ...
                'Name', 'Vertices',                                     ...
                'Type', @steno3d.traits.Array,                          ...
                'Doc', 'Mesh1D vertices',                               ...
                'Shape', {{'*', 3}},                                    ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Segments',                                     ...
                'Type', @steno3d.traits.Array,                          ...
                'Doc', 'Mesh1D segment endpoint indices',               ...
                'Shape', {{'*', 2}},                                    ...
                'DataType', 'int',                                      ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Mesh1D options',                                ...
                'Class', @steno3d.core.line.Mesh1DOptions,              ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
    end

end

