classdef VolumeOptions < steno3d.traits.HasTraits
%VOLUMEOPTIONS Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        VOptTraits = {                                                  ...
            struct(                                                     ...
                'Name', 'Color',                                        ...
                'Type', @steno3d.traits.Color,                          ...
                'Doc', 'Solid volume color',                            ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opacity',                                      ...
                'Type', @steno3d.traits.Number,                         ...
                'Doc', 'Volume opacity',                                ...
                'MinValue', 0,                                          ...
                'MaxValue', 1,                                          ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
    end

end

