classdef Volume < steno3d.core.CompositeResource
%VOLUME Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        VolumeTraits = {                                                ...
            struct(                                                     ...
                'Name', 'Mesh',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Volume mesh',                                   ...
                'Klass', @steno3d.core.volume.Mesh3DGrid,               ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @steno3d.traits.Repeated,                       ...
                'Doc', 'Volume data',                                   ...
                'TraitType', struct(                                    ...
                    'Type', @steno3d.traits.Instance,                   ...
                    'Klass', @steno3d.core.volume.VolumeBinder          ...
                ),                                                      ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Volume Options',                                ...
                'Klass', @steno3d.core.volume.VolumeOptions,            ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
    end

end

