classdef Mesh0D < steno3d.core.UserContent
%MESH0D Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        M0DTraits = {                                                   ...
            struct(                                                     ...
                'Name', 'Vertices',                                     ...
                'Type', @steno3d.traits.Array,                          ...
                'Doc', 'Mesh0D vertices',                               ...
                'Shape', {{'*', 3}},                                    ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Mesh0D options',                                ...
                'Class', @steno3d.core.point.Mesh0DOptions,             ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
    end

end

