classdef Point < steno3d.core.CompositeResource
%POINT Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        PointTraits = {                                                 ...
            struct(                                                     ...
                'Name', 'Mesh',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Point mesh',                                    ...
                'Klass', @steno3d.core.point.Mesh0D,                    ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @steno3d.traits.Repeated,                       ...
                'Doc', 'Point data',                                    ...
                'TraitType', struct(                                    ...
                    'Type', @steno3d.traits.Instance,                   ...
                    'Klass', @steno3d.core.point.PointBinder            ...
                ),                                                      ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Textures',                                     ...
                'Type', @steno3d.traits.Repeated,                       ...
                'Doc', 'Point textures',                                ...
                'TraitType', struct(                                    ...
                    'Type', @steno3d.traits.Instance,                   ...
                    'Klass', @steno3d.core.texture.Texture2DImage       ...
                ),                                                      ...
                'Required', false                                        ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Point Options',                                 ...
                'Klass', @steno3d.core.point.PointOptions,              ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
    end

end

