classdef PointOptions < steno3d.core.Options
%POINTOPTIONS Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        POptTraits = {                                                  ...
            struct(                                                     ...
                'Name', 'Color',                                        ...
                'Type', @steno3d.traits.Color,                          ...
                'Doc', 'Point color',                                   ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opacity',                                      ...
                'Type', @steno3d.traits.Float,                          ...
                'Doc', 'Point opacity',                                 ...
                'MinValue', 0,                                          ...
                'MaxValue', 1,                                          ...
                'Required', false,                                      ...
                'DefaultValue', 1                                       ...
            )                                                           ...

        }
    end

    methods
        function obj = PointOptions(varargin)
            obj = obj@steno3d.core.Options(varargin{:});
        end
    end

end

