classdef PointBinder < steno3d.traits.HasTraits
%POINTBINDER Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        PBinderTraits = {                                               ...
            struct(                                                     ...
                'Name', 'Location',                                     ...
                'Type', @steno3d.traits.String,                         ...
                'Doc', 'Location of the data on mesh',                  ...
                'Choices', struct(                                      ...
                    'N', {{'VERTEX', 'NODE', 'CC', 'CELLCENTER'}}       ...
                ),                                                      ...
                'DefaultValue', 'N',                                    ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @steno3d.traits.Instance,                       ...
                'Doc', 'Point data array',                              ...
                'Klass', @steno3d.core.data.DataArray,                  ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
    end

end

