classdef DataArray < steno3d.core.UserContent
%DATAARRAY Steno3D object to hold data array, ordering, title, etc.

    properties (Hidden, SetAccess = immutable)
        DataArrayProps = {                                              ...
            struct(                                                     ...
                'Name', 'Array',                                        ...
                'Type', @props.Array,                                   ...
                'Doc', 'Data corresponding to points on the mesh',      ...
                'Shape', {{'*', 1}},                                    ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Order',                                        ...
                'Type', @props.String,                                  ...
                'Doc', 'Data array order, for data on grid meshes',     ...
                'Choices', struct(                                      ...
                    'c', {{'c-style', 'numpy', 'row-major', 'row'}},    ...
                    'f', {{'fortran', 'matlab', 'column-major',         ...
                           'column', 'col'}}                            ...
                ),                                                      ...
                'DefaultValue', 'f',                                    ...
                'Lowercase', true,                                      ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
        function obj = DataArray(varargin)
            if rem(nargin, 2) == 1 && isnumeric(varargin{1})
                varargin = [{'Array'} varargin];
            end
            obj = obj@steno3d.core.UserContent(varargin{:});
        end
    end

    methods (Hidden)
        function rc = resourceClass(obj)
            rc = 'array';
        end

        function mapi = modelAPILocation(obj)
            mapi = ['resource/data/' obj.resourceClass];
        end

        function args = uploadArgs(obj)

            args = {'order', obj.Order};
            arrayStruct = obj.PR_Array.serialize();
            args = [args, {'array', arrayStruct.FileID,                 ...
                           'arrayType', arrayStruct.DType}];

            args = [args, uploadArgs@steno3d.core.UserContent(obj)];
        end
    end

end

