classdef Line < steno3d.core.CompositeResource
%LINE Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        LineProps = {                                                  ...
            struct(                                                     ...
                'Name', 'Mesh',                                         ...
                'Type', @props.Instance,                       ...
                'Doc', 'Line mesh',                                     ...
                'Class', @steno3d.core.Mesh1D,                     ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Repeated,                       ...
                'Doc', 'Line data',                                     ...
                'PropType', struct(                                    ...
                    'Type', @props.Instance,                   ...
                    'Class', @steno3d.core.binders.LineBinder,             ...
                    'Initialize', false                                 ...
                ),                                                      ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @props.Instance,                       ...
                'Doc', 'Line Options',                                  ...
                'Class', @steno3d.core.opts.LineOptions,                ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = Line(varargin)
            obj = obj@steno3d.core.CompositeResource(varargin{:});
        end
    end

end

