classdef Line < steno3d.core.CompositeResource
%LINE Steno3D line composite resource

    properties (Hidden, SetAccess = immutable)
        LineProps = {                                                   ...
            struct(                                                     ...
                'Name', 'Mesh',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Line mesh',                                     ...
                'Class', @steno3d.core.Mesh1D,                          ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Repeated,                                ...
                'Doc', 'Line data',                                     ...
                'PropType', struct(                                     ...
                    'Type', @props.Instance,                            ...
                    'Class', @steno3d.core.binders.LineBinder,          ...
                    'Initialize', false                                 ...
                ),                                                      ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Line Options',                                  ...
                'Class', @steno3d.core.opts.LineOptions,                ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = Line(varargin)
            obj = obj@steno3d.core.CompositeResource(varargin{:});
        end
    end

    methods (Hidden)
        function plot(obj)
            if isempty(obj.Data)
                cdata = {'EdgeColor', obj.Opts.Color/255};
            elseif strcmp(obj.Data{1}.Location, 'CC')
                ccarr = obj.Data{1}.Data.Array;
                narr = ccarr(1)*ones(size(obj.Mesh.Vertices, 1), 1);
                narr(obj.Mesh.Segments(:, 1)) = ccarr;
                cdata = {'CData', narr, 'EdgeColor', 'flat'};
            else
                cdata = {'CData', obj.Data{1}.Data.Array,               ...
                         'EdgeColor', 'interp'};
            end

            patch('Faces', obj.Mesh.Segments,                           ...
                  'Vertices', obj.Mesh.Vertices,                        ...
                  cdata{:}, 'EdgeAlpha', obj.Opts.Opacity)
        end
    end
end

