classdef Mesh0D < steno3d.core.UserContent
%MESH0D Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        M0DProps = {                                                   ...
            struct(                                                     ...
                'Name', 'Vertices',                                     ...
                'Type', @props.Array,                          ...
                'Doc', 'Mesh0D vertices',                               ...
                'Shape', {{'*', 3}},                                    ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @props.Instance,                       ...
                'Doc', 'Mesh0D options',                                ...
                'Class', @steno3d.core.opts.Mesh0DOptions,             ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
        function obj = Mesh0D(varargin)
            obj = obj@steno3d.core.UserContent(varargin{:});
        end
    end

    methods (Hidden)
        function args = uploadArgs(obj)

            vStruct = obj.PR_Vertices.serialize();
            args = {'vertices', vStruct.FileID,                         ...
                    'verticesType', vStruct.DType};

            args = [args, uploadArgs@steno3d.core.UserContent(obj)];
        end

    end

end

