classdef Mesh1D < steno3d.core.UserContent
%MESH1D Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        M1DProps = {                                                   ...
            struct(                                                     ...
                'Name', 'Vertices',                                     ...
                'Type', @props.Array,                          ...
                'Doc', 'Mesh1D vertices',                               ...
                'Shape', {{'*', 3}},                                    ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Segments',                                     ...
                'Type', @props.Array,                          ...
                'Doc', 'Mesh1D segment endpoint indices',               ...
                'Shape', {{'*', 2}},                                    ...
                'DataType', 'int',                                      ...
                'Serial', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @props.Instance,                       ...
                'Doc', 'Mesh1D options',                                ...
                'Class', @steno3d.core.opts.Mesh1DOptions,              ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
        function obj = Mesh1D(varargin)
            obj = obj@steno3d.core.UserContent(varargin{:});
        end
    end

    methods (Hidden)
        function args = uploadArgs(obj)

            vStruct = obj.PR_Vertices.serialize();
            sStruct = obj.PR_Segments.serialize();
            args = {'vertices', vStruct.FileID,              ...
                    'verticesType', vStruct.DType,           ...
                    'segments', sStruct.FileID,              ...
                    'segmentsType', sStruct.DType};

            args = [args, uploadArgs@steno3d.core.UserContent(obj)];
        end
    end

end

