classdef Mesh2D < steno3d.core.UserContent
%MESH2D Mesh for steno3d Surface

    properties (Hidden, SetAccess = immutable)
        M2DProps = {                                                    ...
            struct(                                                     ...
                'Name', 'Vertices',                                     ...
                'Type', @props.Array,                                   ...
                'Doc', 'Mesh2D vertices',                               ...
                'Shape', {{'*', 3}},                                    ...
                'Binary', true,                                         ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Triangles',                                    ...
                'Type', @props.Array,                                   ...
                'Doc', 'Mesh2D triangle vertex indices',                ...
                'Shape', {{'*', 3}},                                    ...
                'DataType', 'int',                                      ...
                'Binary', true,                                         ...
                'IndexArray', true,                                     ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Mesh2D options',                                ...
                'Class', @steno3d.core.opts.Mesh2DOptions,              ...
                'Required', false                                       ...
            )                                                           ...

        }
    end

    methods
        function obj = Mesh2D(varargin)
            obj = obj@steno3d.core.UserContent(varargin{:});
        end
        
        function n = nN(obj)
            n = length(obj.Vertices);
        end
        function n = nC(obj)
            n = length(obj.Triangles);
        end
        function n = nbytes(obj)
            n = length(obj.Vertices(:))*8 + length(obj.Triangles(:))*8;
        end
    end

    methods (Hidden)
        
        function validator(obj)
            if min(obj.Triangles(:)) < 1 ||                             ...
                    max(obj.Triangles(:)) > size(obj.Vertices, 1)
                error('steno3d:validationError',                        ...
                      ['Triangles must be integers between 1 and '      ...
                       num2str(size(obj.Vertices, 1))                   ...
                       ' (length of vertices)'])
            end
            if steno3d.utils.User.isLoggedIn()
                user = steno3d.utils.User.currentUser();
                sz = max([obj.([obj.PROP_PREFIX 'Vertices']).nbytes     ...
                          obj.([obj.PROP_PREFIX 'Triangles']).nbytes]);
                if sz > user.FileSizeLimit
                    error('steno3d:validationError',                    ...
                          ['File size ' num2str(sz) ' bytes exceeds '   ...
                           'file limit of ' num2str(user.FileSizeLimit) ...
                           ' bytes']);
                end
            end
        end
        function args = uploadArgs(obj)

            vStruct = obj.PR_Vertices.serialize();
            tStruct = obj.PR_Triangles.serialize();
            args = {'vertices', vStruct.FileID,                         ...
                    'verticesType', vStruct.DType,                      ...
                    'triangles', tStruct.FileID,                        ...
                    'trianglesType', tStruct.DType};

            args = [args, uploadArgs@steno3d.core.UserContent(obj)];
        end
    end

end

