classdef Point < steno3d.core.CompositeResource
%POINT Steno3D Point composite resource

    properties (Hidden, SetAccess = immutable)
        PointProps = {                                                  ...
            struct(                                                     ...
                'Name', 'Mesh',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Point mesh',                                    ...
                'Class', @steno3d.core.Mesh0D,                          ...
                'Required', true                                        ...
            ), struct(                                                  ...
                'Name', 'Data',                                         ...
                'Type', @props.Repeated,                                ...
                'Doc', 'Point data',                                    ...
                'PropType', struct(                                     ...
                    'Type', @props.Instance,                            ...
                    'Class', @steno3d.core.binders.PointBinder,         ...
                    'Initialize', false                                 ...
                ),                                                      ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Textures',                                     ...
                'Type', @props.Repeated,                                ...
                'Doc', 'Point textures',                                ...
                'PropType', struct(                                     ...
                    'Type', @props.Instance,                            ...
                    'Class', @steno3d.core.Texture2DImage,              ...
                    'Initialize', false                                 ...
                ),                                                      ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opts',                                         ...
                'Type', @props.Instance,                                ...
                'Doc', 'Point Options',                                 ...
                'Class', @steno3d.core.opts.PointOptions,               ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = Point(varargin)
            obj = obj@steno3d.core.CompositeResource(varargin{:});
        end
    end

    methods (Hidden)
        function plot(obj)
            if ~isempty(obj.Data)
                scatter3(obj.Mesh.Vertices(:, 1),                       ...
                         obj.Mesh.Vertices(:, 2),                       ...
                         obj.Mesh.Vertices(:, 3), [],                   ...
                         obj.Data{1}.Data.Array(:), 'filled',           ...
                         'MarkerFaceAlpha', obj.Opts.Opacity);
            else
                scatter3(obj.Mesh.Vertices(:, 1),                       ...
                         obj.Mesh.Vertices(:, 2),                       ...
                         obj.Mesh.Vertices(:, 3), [],                   ...
                         obj.Opts.Color/255, 'filled',                  ...
                         'MarkerFaceAlpha', obj.Opts.Opacity);
            end
        end
    end



end

