classdef LineOptions < steno3d.core.opts.Options
%LINEOPTIONS Options for Steno3D Line objects
%   For usage details, see the %%%ref[options help](steno3d.core.opts).
%
%   %%%properties
%
%   See the line %%%ref[EXAMPLES](steno3d.core.examples.line)
%
%   %%%seealso STENO3D.CORE.OPTS, STENO3D.CORE.LINE
%


    properties (Hidden, SetAccess = immutable)
        LOptProps = {                                                   ...
            struct(                                                     ...
                'Name', 'Color',                                        ...
                'Type', @props.Color,                                   ...
                'Doc', 'Solid line color',                              ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opacity',                                      ...
                'Type', @props.Float,                                   ...
                'Doc', 'Line opacity',                                  ...
                'MinValue', 0,                                          ...
                'MaxValue', 1,                                          ...
                'Required', false,                                      ...
                'DefaultValue', 1                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = LineOptions(varargin)
            obj = obj@steno3d.core.opts.Options(varargin{:});
        end
    end
end


