classdef PointOptions < steno3d.core.opts.Options
%POINTOPTIONS Options for Steno3D Point objects
%   For usage details, see the %%%ref[options help](steno3d.core.opts).
%
%   %%%properties
%
%   See the point %%%ref[EXAMPLES](steno3d.examples.core.point)
%
%   %%%seealso steno3d.core.opts, steno3d.core.Point
%


    properties (Hidden, SetAccess = immutable)
        POptProps = {                                                   ...
            struct(                                                     ...
                'Name', 'Color',                                        ...
                'Type', @props.Color,                                   ...
                'Doc', 'Point color',                                   ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opacity',                                      ...
                'Type', @props.Float,                                   ...
                'Doc', 'Point opacity',                                 ...
                'MinValue', 0,                                          ...
                'MaxValue', 1,                                          ...
                'Required', false,                                      ...
                'DefaultValue', 1                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = PointOptions(varargin)
            obj = obj@steno3d.core.opts.Options(varargin{:});
        end
    end
end


