classdef VolumeOptions < steno3d.core.opts.Options
%VOLUMEOPTIONS Options for Steno3D Volume objects
%   For usage details, see the %%%ref[options help](steno3d.core.opts).
%
%   %%%properties
%
%   See the volume %%%ref[EXAMPLES](steno3d.examples.core.volume)
%
%   %%%seealso steno3d.core.opts, steno3d.core.Volume
%


    properties (Hidden, SetAccess = immutable)
        VOptProps = {                                                   ...
            struct(                                                     ...
                'Name', 'Color',                                        ...
                'Type', @props.Color,                                   ...
                'Doc', 'Solid volume color',                            ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opacity',                                      ...
                'Type', @props.Float,                                   ...
                'Doc', 'Volume opacity',                                ...
                'MinValue', 0,                                          ...
                'MaxValue', 1,                                          ...
                'Required', false,                                      ...
                'DefaultValue', 1                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = VolumeOptions(varargin)
            obj = obj@steno3d.core.opts.Options(varargin{:});
        end
    end
end


