classdef Mesh2DOptions < steno3d.core.opts.Options
%MESH2DOPTIONS Options applicable for steno3d Mesh2D or Mesh2DGrid

    properties (Hidden, SetAccess = immutable)
        M2DOptProps = {                                                 ...
            struct(                                                     ...
                'Name', 'Wireframe',                                    ...
                'Type', @props.Bool,                                    ...
                'Doc', 'Display 2D mesh wireframe',                     ...
                'DefaultValue', false,                                  ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods
        function obj = Mesh2DOptions(varargin)
            obj = obj@steno3d.core.opts.Options(varargin{:});
        end
    end

end

