classdef Mesh3DOptions < steno3d.core.opts.Options
%MESH3DOPTIONS Options applicable for steno3d Mesh3DGrid

    properties (Hidden, SetAccess = immutable)
        M3DOptProps = {                                                 ...
            struct(                                                     ...
                'Name', 'Wireframe',                                    ...
                'Type', @props.Bool,                                    ...
                'Doc', 'Display 3D mesh wireframe',                     ...
                'DefaultValue', false,                                  ...
                'Required', false                                       ...
            )                                                           ...
        }
    end

    methods

        function obj = Mesh3DOptions(varargin)
            obj = obj@steno3d.core.opts.Options(varargin{:});
        end
    end

end

