classdef SurfaceOptions < steno3d.core.opts.Options
%SURFACEOPTIONS Options applicable to steno3d Surface

    properties (Hidden, SetAccess = immutable)
        SOptProps = {                                                   ...
            struct(                                                     ...
                'Name', 'Color',                                        ...
                'Type', @props.Color,                                   ...
                'Doc', 'Solid surface color',                           ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Opacity',                                      ...
                'Type', @props.Float,                                   ...
                'Doc', 'Surface opacity',                               ...
                'MinValue', 0,                                          ...
                'MaxValue', 1,                                          ...
                'Required', false,                                      ...
                'DefaultValue', 1                                       ...
            )                                                           ...

        }
    end

    methods

        function obj = SurfaceOptions(varargin)
            obj = obj@steno3d.core.opts.Options(varargin{:});
        end
    end

end

