
steno3d.login;

pks = peaks(20);
sfc = steno3d.core.Surface(                                  ...
    'Title', 'Example 5 Grid',                               ...
    'Description', 'This Surface resource will have data',   ...
    'Mesh', {                                                ...
        'H1', 2*ones(19, 1),                                 ...
        'H2', 3*ones(19, 1),                                 ...
        'O', [-19 0 -28.5],                                  ...
        'U', [1 0 0],                                        ...
        'V', [.5 0 sqrt(3)/2],                               ...
        'Z', pks(:)                                          ...
    },                                                       ...
    'Opts', {'Color', 'y', 'Opacity', 0.75},                 ...
    'Data', {{                                               ...
        'Location', 'N',                                     ...
        'Data', {'Title', 'Peaks Data', 'Array', pks(:)}     ...
    }, {                                                     ...
        'Location', 'CC',                                    ...
        'Data', {'Title', 'Random', 'Array', rand(19*19, 1)} ...
    }},                                                      ...
    'Textures', {{                                           ...
        'Title', 'Aligned image',                            ...
        'Image', 'ngc6543a.jpg',                             ...
        'U', 38*[1 0 0],                                     ...
        'V', 57*[.5 0 sqrt(3)/2],                            ...
        'O', [-19 0 -28.5]                                   ...
    }, {                                                     ...
        'Title', 'Small square image',                       ...
        'Image', 'ngc6543a.jpg',                             ...
        'O', [-.5 0 -20],                                    ...
        'U', 'X',                                            ...
        'V', 'Z'                                             ...
    }}                                                       ...
);
example5 = steno3d.core.Project(                             ...
    'Title', 'Example 5',                                    ...
    'Description', 'Project with a surface',                 ...
    'Resources', sfc                                         ...
);
example5.plot;
clear sfc;



% xlim([0 1])
% ylim([0 1])
% zlim([-8 8])

ax = gca;
ax.FontWeight = 'bold';
ax.FontSize = 12;
ax.LineWidth = 1.5;
ax.XGrid = 'on';
ax.YGrid = 'on';
ax.ZGrid = 'on';
ax.XLabel.String = 'X axis';
ax.XLabel.FontSize = 14;
ax.YLabel.String = 'Y axis';
ax.YLabel.FontSize = 14;
ax.ZLabel.String = 'Z axis';
ax.ZLabel.FontSize = 14;
ax.Color = [1 1 1];
ax.TickLength = [0.02 0.02];
ax.Box = 'on';
legend('hide')
% xticks([0 5 10 15 20])
campos([44.1127  -12.0908   10.8531])
print('-dpng','-r500','image')

example5.upload();


