classdef UserContent < steno3d.traits.HasTraits
%USERCONTENT Summary of this class goes here
%   Detailed explanation goes here

    properties (Hidden, SetAccess = immutable)
        UCTraits = {                                                    ...
            struct(                                                     ...
                'Name', 'Title',                                        ...
                'Type', @steno3d.traits.String,                         ...
                'Doc', 'Content title',                                 ...
                'DefaultValue', '',                                     ...
                'Required', false                                       ...
            ), struct(                                                  ...
                'Name', 'Description',                                  ...
                'Type', @steno3d.traits.String,                         ...
                'Doc', 'Content description',                           ...
                'DefaultValue', '',                                     ...
                'Required', true                                        ...
            )                                                           ...
        }
    end

    methods
    end

    methods (Hidden)
        function rc = resourceClass(obj)
            mc = metaclass(obj);
            rcfull = strsplit(mc.Name, '.');
            rc = rcfull{end};
        end

        function mapi = modelAPILocation(obj)
            mapi = ['resource/' obj.ResourceClass];
        end



    end

end

